name: CI 자동화 테스트

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle 명령 실행을 위한 권한을 부여합니다
      run: chmod +x gradlew
    
    - name: Gradle build를 수행합니다
      run: ./gradlew build

  notification:
    name: 빌드 결과 slack 푸시 알림 전송
    runs-on: ubuntu-latest
    if: ${{ always() }}  #성공하든 실패하든 항상 notification Job 실행
    needs: [ build ] #job들의 id들을 적어줍니다.
    steps:
      - uses: martialonline/workflow-status@v3
        id: check
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Bot
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Webhook Secret Key
        if: always()
